version: '2.3'

services:
  face_recognition:
    image: face_recognition
    container_name: face_recognition
    working_dir: /face_recognition/examples
    build:
      context: .
      #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
      # dockerfile: Dockerfile.gpu 
    command: python3 -u extract_keypoints.py /media/Utterances /media/FaceKeypoints
    volumes:
      - ./:/face_recognition
      - /media/quadserver2/data/paul/face/OMGEmotion:/media
    #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
    # runtime: nvidia